# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(335, 194)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.RunScript = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RunScript.setObjectName("RunScript")
        self.gridLayout.addWidget(self.RunScript, 6, 0, 1, 3)
        self.SelectFile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SelectFile.setObjectName("SelectFile")
        self.gridLayout.addWidget(self.SelectFile, 0, 2, 1, 1)
        self.filePath = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.filePath.setReadOnly(True)
        self.filePath.setObjectName("filePath")
        self.gridLayout.addWidget(self.filePath, 0, 0, 1, 2)
        self.KursEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.KursEdit.setEnabled(True)
        self.KursEdit.setObjectName("KursEdit")
        self.gridLayout.addWidget(self.KursEdit, 5, 1, 1, 1)
        self.kursText = QtWidgets.QLabel(parent=self.centralwidget)
        self.kursText.setObjectName("kursText")
        self.gridLayout.addWidget(self.kursText, 5, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 335, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RunScript.setText(_translate("MainWindow", "Начать"))
        self.SelectFile.setText(_translate("MainWindow", "Выбрать файл"))
        self.KursEdit.setText(_translate("MainWindow", "90.00"))
        self.kursText.setText(_translate("MainWindow", "Курс"))
